version: "3.9"
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
